require: rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'configure']